# Generated by Django 3.0.7 on 2020-06-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('unique_id', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=30)),
                ('mother_name', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('other', 'other'), ('none', 'None')], default='none', max_length=5)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=15)),
                ('pincode', models.IntegerField(blank=True, default=None, null=True)),
                ('email', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='signup.account', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('post_id', models.UUIDField(null=True)),
                ('username', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='signup.account', to_field='username')),
            ],
        ),
    ]
