# Generated by Django 3.0.7 on 2020-06-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_id',
        ),
    ]
