# Generated by Django 3.0.7 on 2020-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_posts_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_id',
            field=models.UUIDField(default=None),
        ),
    ]
