# Generated by Django 3.0.7 on 2020-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_posts_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
    ]
